# AUTOGENERATED
		def	QCEDO-0,0,'R\left(- \frac{225 t}{4}\right)'
		def	QCEDO-1,0,'R\left(\frac{135 t}{4}\right)'
		def	QCEDO-2,0,'R\left(- \frac{153 t}{4}\right)'
		def	QCEDO-3,0,'R\left(\frac{51 t}{4}\right)'
		def	QCEDO-4,0,'R\left(- \frac{45 t}{4}\right)'
		def	QCEDO-5,0,'R\left(\frac{75 t}{4}\right)'
		def	QCEDO-6,0,'R\left(- \frac{85 t}{4}\right)'
		qubit	q0
		qubit	q1
		qubit	q2
		QCEDO-0	q0
		cnot	q0,q1
		QCEDO-1	q1
		cnot	q0,q1
		QCEDO-2	q1
		cnot	q1,q2
		QCEDO-3	q2
		cnot	q0,q2
		QCEDO-4	q2
		cnot	q1,q2
		QCEDO-5	q2
		cnot	q0,q2
		QCEDO-6	q2
